apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: ldap
          image: bitnami/openldap:2
          ports:
            - containerPort: 1389
              name: openldap  
          env:
            - name: LDAP_ADMIN_USERNAME
              value: "admin"
            - name: LDAP_ROOT
              value: "dc=example,dc=org"
            - name: LDAP_ADMIN_PASSWORD
              value: "password"
            - name: LDAP_CUSTOM_LDIF_DIR
              value: "/myldifs"  
            - name: LDAP_LOGLEVEL
              value: "256" 
            - name: BITNAMI_DEBUG
              value: "0"  
          volumeMounts:
            - name: bootstrapdir
              mountPath: /myldifs
              subpath: custom.ldif
      volumes:
        - name: bootstrapdir
          configMap:
            name: bootstrap
            items: 
            - key: bootstrap.ldif
              path: custom.ldif        
            